### ISSUE TITLE
Classroom API

### ISSUE THREAD

**Issue by brmiller01** [emerginganalytics/cyberarena#100]
Put together the Classroom API

**Comment by abbomberger** [comment]
Basic overview of what the classroom API should accomplish: 
- Methods (routes) should only be accessible by instructors and admins
- GET:  
    - `class_name` is given with request, returns single `cybergym-class` datastore object
    - `class_name` not given, return all classes for that instructor 
- POST: 
    -  Creates `cybergym-class` datastore Entity for requesting instructor
- DELETE: 
    - If requesting user is owner of the classroom or an admin, delete requested classroom
    - If user fails above check, return 403
    - Return `400` if `class_name` is not in request
- PUT: 
    - If `class_name`, update student roster for single class. This can be either updating individual student or multiple.
    - if not `class_name`, return `400` for now.


As with the other APIs, we want to make sure that any cloud specific code is kept to the respective cloud class (i.e gcp.datastore_manager). 

Eventually (not needed for now), it would be nice to be able to read from a CSV file to update multiple students in a classroom.  This logic can be moved to its own class

**Comment by pdhuff** [comment]
[API Architecture](https://github.com/emerginganalytics/cyberarena/blob/master/design-files/fixed-arena-architcture.drawio.png)
