### ISSUE TITLE
LMS Integration

### ISSUE THREAD

**Issue by pdhuff** [emerginganalytics/cyberarena#184]
Provide a way to integrate lab questions with an LMS. Initially, we will develop for Canvas a versatile (i.e., polymorphic) class, which will allow us to develop a child class for Blackboard in the near future. The following changes are needed for this task:
1. **Schema:** Create the schema for an LMS add-on in the unit schema that allows for assignments and questions.
2. **Instructor Variables:** Add instructor variables to the Datastore record that are needed for LMS integration in a Google project, such as URL and API_Key. If these do not exist, then we need to raise an understandable error, like "LMS integration is not configured for this site. Please contact your system administrator"
3. **Quiz Creation Front End:** When a unit has LMS integration, allow the instructor to select the course and assignment details on the front end. Include front-end fields for: points (double), due_at (DateTime), and allowed_attempts (int). The name, description, and type will be automatically filled-in.
4. **LMS Front-End API:** Provide basic functions to interact with the API and pull back possible course assignments. However, most of the work of creating the new assignment for students will occur on the backend cloud function.
5. **Quiz Creation Back End Cloud Function:** Post request with all the quiz data will trigger the creation of a new assignment with all of the indicated questions. Pull back the class list for automatic assignment and automatically build the workouts on the backend. This will require some modifications to build everything for the unit up front rather than the default approach to allow students to select. However, we still want the join code for students, and they will need to enter their valid email address to receive their assignment. This will be problematic because students will certainly enter a different email occasionally. We might want to generate an email to the students with a link to their lab.
6. **Grading (Front end):** The quiz questions will be submitted individually, and we must add a new button for final submission. The student ID and the quiz ID need to be stored with the workout.
> **NOTE** I think we should strike this task number 6. We'll be better off letting the LMS do its own grading rather than trying to recreate the quiz submission page.
8. **Auto-Submit:** We need the auto assessment to submit a completion status for autocomplete questions. This will require a randomly generated answer in a quiz that only the auto-assessment can submit. Also, the auto-submit will submit the quiz if all questions have been answered. Otherwise, students can manually click submit from their workout if they cannot figure out some of the automated assessment items.

**Comment by brmiller01** [comment]
I'll start on part 3

**Comment by pdhuff** [comment]
The cloud functions still need work as of today. I have most of the code put in to create the quiz, but the following functions (at least) are still needed:
1. Create the workout when a student first logs in.
2. Give the user a friendly message if their email address is not with the unit. In the current app, we just create a new workout
3. Tie in the front end to `v2/main_app/api/unit.py` for the LMS.
4. Lots more debugging messages and testing
5. Auto-grade questions that have assessment scripts.
