### ISSUE TITLE
Admin Maintenance Page QOL Updates

### ISSUE THREAD

**Issue by 0xfut1le** [emerginganalytics/cyberarena#50]
After projects accumulate large number of built workouts, the admin maintenance page has a slower initial load time and manually filtering through items can be a bit tedious.

It would be nice to implement the following functionality: 
- Add pagination to help reduce overall load times
- Allow table sorting by [ workout_id, workout_type, unit_id, instructor ]

Bugs:   
- The student_name field is not being correctly parsed and displays the object instead of object value

**Comment by brmiller01** [comment]
Update to Bug:
The student_name bug seems to happen on 2fa workouts only, doing some more testing to make sure,
